[package]
name = "url_utilities"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = {path="../shared"}
tags = {path="../tags"}
itertools = "0.10.0"
validator = "0.14.0"