

test_meta_test:
	RAYON_NUM_THREADS=2 cargo run --release --bin test -- meta_test ../honggfuzz/hfuzz_workspace/meta_test/

test_from_vec:
	RAYON_NUM_THREADS=2 cargo run --release --bin test -- from_vec ../honggfuzz/hfuzz_workspace/from_vec

test_from_csv:
	RAYON_NUM_THREADS=2 cargo run --release --bin test -- from_csv ../honggfuzz/hfuzz_workspace/from_csv/