[package]
name = "gpu_models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cuda-driver-sys="0.3.0"
cuda-runtime-sys="0.3.0-alpha.1"

[profile.release]
debug = true
