version: "3.8"
services:
  jupyter:
    build:
      context: ./
      dockerfile: ./JupyterDocker
    command: /root/anaconda3/bin/jupyter notebook --no-browser --allow-root --ip=0.0.0.0 --port=10000
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - video
    security_opt:
      - seccomp:unconfined
    ports:
      - "10000:10000"
    volumes:
      - ./:/io