/// The path to the PTX generated by the GPU code
pub const PTX_SOURCE: &str = include_str!("../../cuda_kernels/target/nvptx64-nvidia-cuda/release/cuda_kernels.ptx");

mod node2vec;
mod cbow;
mod skipgram;
pub use cbow::*;
pub use skipgram::*;

mod wrappers;
pub use wrappers::*;