/// The path to the PTX generated by the GPU code
const PTX: &str = include_str!("../../cuda_kernels/target/nvptx64-nvidia-cuda/release/cuda_kernels.ptx");

mod cbow;
pub use cbow::*;
mod wrappers;
pub use wrappers::*;