[package]
name = "shared"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.1"
indicatif = {version="0.16.0", features = ["rayon"]}
